steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "asia-southeast2-docker.pkg.dev/symmetric-ace-303411/k8s/hello-world:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "asia-southeast2-docker.pkg.dev/symmetric-ace-303411/k8s/hello-world:latest"
