apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: app
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: asia-southeast2-docker.pkg.dev/symmetric-ace-303411/k8s/hello-world
          ports:
            - containerPort: 3000
